# Generated by Django 4.2.17 on 2026-06-25 19:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'info'), ('new_job', 'New Job Post'), ('job_apply', 'Job Application'), ('verify_request', 'Verification Request'), ('verify_response', 'Verification Response'), ('new_booking', 'New Booking'), ('new_job_request', 'New Job Request'), ('new_job_response', 'Job Request Response'), ('new_complain', 'New Complaint'), ('new_feedback', 'New Feedback'), ('new_review', 'New Review')], default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
